config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: :registrations }

    root 'events#index'

    resources :events do
      resources :comments, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]
      resources :photos, only: %i[create destroy]

      post :show, on: :member
    end

    resources :users, only: %i[show edit update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :name, presence: true, length: { maximum: 35 }
  validates :email, length: { maximum: 255 }, uniqueness: true, format: /\A[^@\s]+@(?:[-a-z0-9]+\.)+[a-z]{2,}\z/i

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  private

  def set_name
    self.name = "Товарисч №#{rand(777)}" if name.blank?
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: email).update_all(user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit; end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true, class: 'panel panel-default' } do |f| %>
  <div class="panel-heading">
    <h1 class="panel-title"><strong><%= t('.title') %></strong></h1>
  </div>

  <div class="panel-body">
    <div class="form-group <%= "has-error" if f.errors_on?(:name) %>">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_span(:name) %>
    </div>

    <div class="form-group <%= "has-error" if f.errors_on?(:email) %>">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.error_span(:email) %>
    </div>

    <div class="form-group <%= "has-error" if f.errors_on?(:avatar) %>">
      <%= f.label :avatar %>
      <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
      <%= f.file_field :avatar %>
      <%= f.error_span(:avatar) %>
    </div>

    <div class="actions">
      <%= f.submit t('.buttons.save'), class: 'btn btn-primary' %>
      <%= t('.or_label') %>
      <%= link_to t('.links.back'), :back %>
    </div>
  </div>

  <div class="panel-footer">
    <%= link_to t('.links.change_password'), edit_user_registration_path %><br>
    <%= link_to t('.links.destroy_page'), registration_path(:user),
                data: { confirm: t('.destroy_confirm') }, method: :delete %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<% content_for :locale_links do  %>
  <p>
    <% I18n.available_locales.each_with_index do |locale, index| %>
      <% if index.zero? %>
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), edit_user_path(@user, locale: locale) %>
      <% else %>
        |
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), edit_user_path(@user, locale: locale) %>
      <% end %>
    <% end %>
  </p>
<% end %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top"><%= button_to t('.buttons.edit'), edit_user_path(@user), method: :get, class: 'btn btn-primary' %></p>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @user.events.any? %>
      <h3><%= t('.organized') %></h3>
      <div class="row">
        <%= render partial: 'events/event', collection: @user.events %>
      </div>
    <% else %>
      <p class="buffer-top"><%= t('.not_organized') %></p>
    <% end %>
  </div>
</div>