config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: :registrations }

    root 'events#index'

    resources :events do
      resources :comments, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]
      resources :photos, only: %i[create destroy]

      post :show, on: :member
    end

    resources :users, only: %i[show edit update]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(event_pincode)
    pincode == event_pincode
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: %i[edit update destroy]
  before_action :password_guard!, only: [:show]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to(@event, notice: I18n.t('controllers.events.created'))
    else
      render(:new)
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to(@event, notice: I18n.t('controllers.events.updated'))
    else
      render(:edit)
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to(events_url, notice: I18n.t('controllers.events.destroyed'))
  end

  private

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user
    return true if @event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    else
      flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
      render 'password_form'
    end
  end

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode, :latitude, :longitude)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event, html: { class: 'panel panel-default' }) do |f| %>
  <div class="panel-heading">
    <h1 class="panel-title"><strong><%= event_title_form(@event) %></strong></h1>
  </div>

  <div class="panel-body">
    <div class="form-group <%= "has-error" if f.errors_on?(:title) %>">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.error_span(:title) %>
    </div>

    <div class="form-group <%= "has-error" if f.errors_on?(:address) %>">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      <%= f.error_span(:address) %>
    </div>

    <div class="form-group <%= "has-error" if f.errors_on?(:datetime) %>">
      <%= f.label :datetime %>
      <div class="form-inline"><%= f.datetime_select :datetime, {}, class: 'form-control' %></div>
      <%= f.error_span(:datetime) %>
    </div>

    <div class="form-group <%= "has-error" if f.errors_on?(:description) %>">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <%= f.error_span(:description) %>
    </div>

    <div class="form-group <%= "has-error" if f.errors_on?(:pincode) %>">
      <%= f.label :pincode %>
      <%= f.text_field :pincode, class: 'form-control' %>
      <%= f.error_span(:pincode) %>
    </div>

    <div class="actions">
      <%= f.submit t('.buttons.save'), class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="panel-footer">
    <%= event_back_link(@event) %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for :locale_links do  %>
  <p>
    <% I18n.available_locales.each_with_index do |locale, index| %>
      <% if index.zero? %>
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), edit_event_path(@event, locale: locale) %>
      <% else %>
        |
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), edit_event_path(@event, locale: locale) %>
      <% end %>
    <% end %>
  </p>
<% end %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buffer-both">
  <%= button_to t('.buttons.create'), new_event_path, method: :get, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<% content_for :locale_links do  %>
  <p>
    <% I18n.available_locales.each_with_index do |locale, index| %>
      <% if index.zero? %>
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), new_event_path(locale: locale) %>
      <% else %>
        |
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), new_event_path(locale: locale) %>
      <% end %>
    <% end %>
  </p>
<% end %>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<% content_for :locale_links do  %>
  <p>
    <% I18n.available_locales.each_with_index do |locale, index| %>
      <% if index.zero? %>
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), event_path(@event, locale: locale) %>
      <% else %>
        |
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), event_path(@event, locale: locale) %>
      <% end %>
    <% end %>
  </p>
<% end %>

<h1><%= t('.title') %></h1>

<%= form_tag('', method: 'post') do %>
  <div class="form-group">
    <%= label t('.label'), :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag t('.buttons.check'), class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="buffer-top">
  <%= link_to t('.links.main'), events_path %>
</div>

app/views/events/show.html.erb
<% content_for :locale_links do  %>
  <p>
    <% I18n.available_locales.each_with_index do |locale, index| %>
      <% if index.zero? %>
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), event_path(@event, locale: locale) %>
      <% else %>
        |
        <%= link_to_unless I18n.locale == locale, t("app.locale.#{locale}"), event_path(@event, locale: locale) %>
      <% end %>
    <% end %>
  </p>
<% end %>

<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address, "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="flex buffer-both">
              <%= button_to t('.buttons.change'), edit_event_path(@event), method: :get, class: 'btn btn-primary' %>
              <%= button_to t('.buttons.destroy'), event_path(@event), method: :delete,
                          data: { confirm: t('.destroy_confirm') }, class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>

        <div class="col-md-6">
          <div class="event-map" id="map" data-address='<%= @event.address %>'>
            <% if I18n.locale == :en %>
              <%= map(center: { latlng: [@event.latitude, @event.longitude], zoom: 14 },
                      markers: [{ latlng: [@event.latitude, @event.longitude], popup: @event.address }],
                      attribution: "Map data &copy; #{link_to('OpenStreetMap', 'https://www.openstreetmap.org')} contributors",
                      tile_layer: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
                      max_zoom: 18) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>

        <% if user_signed_in? && event_has_current_subscriber?(@event) || current_user_can_edit?(@event) %>
          <div class="event-photo-form">
            <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
          </div>
        <% end %>
      </div>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4><%= t('.owner') %></h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4><%= t('.participants') %></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription', collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% unless event_has_current_subscriber?(@event) || user_signed_in? && current_user == @event.user %>
        <div class="event-subscription-form">
          <h4><%= t('.join') %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>